language: python
python:
  - 3.5
  - 3.6
os:
  - linux
cache:
  directories:
    - "$HOME/.cache"
virtualenv:
  system_site_packages: true
script: ./build.sh build
install: python setup.py install
deploy:
  provider: pypi
  user: logicify
  distributions: sdist bdist_wheel
  password:
    secure: "rqfgDL2l6kilvsJcgdOHuxtquehYGGIqYmOoVHliZuktikyDlUSi6StwS0Z2midtHyBO8CwmQZcqA9z8BAcPxaI+Nqk+LjspXbnh5/QZXz+e41IShhdTcYmGn1lWgoLa4QdPxIrsSoi9oW34OzIAiuJjr1t0UVUbngRcdGNKXG+xSvH21+4RSOnJP9OZMo5G95VdnKahAarspSjKVBaY8pndo5Pf2YCs/ROuuETbTr7NmtWnfOLPXBWAL/tEsRcRmIF93eZSXoBYRpPlNymODfF9vkBwbmh6ndWbSCExR77Np+0Pyrd3v/QdJnDM7yQy00SFt6JByvAmQGK+QcMeo3u6o9f+nnt3beIf2MgGLh9W6S2wVSIHdfTgXhn0r7zgSIVoakpareF5vZVY5FCUvHKxnosR/4t1StKEMi0MtbgccdFiRnR5OtSJNGKrlZBJNx0I6k7OaFUuXZ7zZE87p+vWi2/vm7W7uTjicrM5ZvU8gFVDd2RBJfd+yLbhgc7sYRAa7srOWrmWm1z2N5E8J35ygKabZqSE5dUFWpL+jDkEfCJEmXxmz15cpxElhfIpXwh8EVG9gFNZNay3NoLCWv1OfhuaAy3GqNEyETrthxRtyHzYiQmzOx1GwxieKLFionfsWMi3+XtfEDDpZAe9tk8Uaff2uKxDEbWIy5W39RU="
  on:
    tags: true