language: python
python:
- 3.5
- 3.6
os:
- linux
cache:
  directories:
  - "$HOME/.cache"
services:
  - docker
script:
- "./build.sh build"
install:
- pip install -r requirements.txt
env:
  global:
  - SKIP_VENV=yes
  - $DOCKER_USERNAME=logicifydeployer
  - secure: noTBKafmvRHe/NYXGS2ef2dMNQV+abQ/WtNMTG+JbFvQ81ugd7cC+PJI52HfDuhCtOnAlsgayLFlc2hDLEmj3M46CwHicyLHbjI5YhH/IzAIwhorF2Ed+sIDjkEM3L4v43egN2tEQ6N6dNsBkn2YenYXmROalS/C081RQ8h1f3miGcUJcmvTveEVf/ff3ijVa/1WZ5qedIRTh6KgwNKJGffUv8v1qyaVsFvE3cu+419V+f32Wg7WBZ4rrx3sFTUQueudgUySavNfLOPW3WkZr/J4coj806yoyNtnbMsDzaMCzAmXLdDEVxLknPuX/eEO1vxOpg69lPYTagLyw9fn7yf1/FkDQojPtkXHKM/y4uKWCyL0UTE14X/UE2TV5z3UCefAropxakvvap9zk8zRuHIOJJ50UEaXy9oA+YypvYPxweWxAH3Q2HEdq32v3PajwA2L9WxDyZjzqStYpJ9l9+0/5cG1W1ZsEYFBxE3OagBcChWzcJ4hnB4Ed+5gSTj9VlgTa+uGpJJAuMvjUNcQTOU78q6GIhwZsQxfFjs5e8F2KPkKSgbaqDRt4aqkS+Lt0yxv0JTCQyawv+EMcJXU0IscQy5eyjx4oN1LLM1zfEvA5dX8fXIYPVxIZKWSMToVlwK8rskKrulpysL2xAp7QzsF27s6opGRqbVcoEiY3fs=
deploy:
  provider: pypi
  user: logicify
  distributions: sdist bdist_wheel
  skip_cleanup: true
  skip_existing: true
  password:
    secure: rqfgDL2l6kilvsJcgdOHuxtquehYGGIqYmOoVHliZuktikyDlUSi6StwS0Z2midtHyBO8CwmQZcqA9z8BAcPxaI+Nqk+LjspXbnh5/QZXz+e41IShhdTcYmGn1lWgoLa4QdPxIrsSoi9oW34OzIAiuJjr1t0UVUbngRcdGNKXG+xSvH21+4RSOnJP9OZMo5G95VdnKahAarspSjKVBaY8pndo5Pf2YCs/ROuuETbTr7NmtWnfOLPXBWAL/tEsRcRmIF93eZSXoBYRpPlNymODfF9vkBwbmh6ndWbSCExR77Np+0Pyrd3v/QdJnDM7yQy00SFt6JByvAmQGK+QcMeo3u6o9f+nnt3beIf2MgGLh9W6S2wVSIHdfTgXhn0r7zgSIVoakpareF5vZVY5FCUvHKxnosR/4t1StKEMi0MtbgccdFiRnR5OtSJNGKrlZBJNx0I6k7OaFUuXZ7zZE87p+vWi2/vm7W7uTjicrM5ZvU8gFVDd2RBJfd+yLbhgc7sYRAa7srOWrmWm1z2N5E8J35ygKabZqSE5dUFWpL+jDkEfCJEmXxmz15cpxElhfIpXwh8EVG9gFNZNay3NoLCWv1OfhuaAy3GqNEyETrthxRtyHzYiQmzOx1GwxieKLFionfsWMi3+XtfEDDpZAe9tk8Uaff2uKxDEbWIy5W39RU=
  on:
    tags: true
after_deploy:
- docker build -t logicify/healthcheckbot:latest -t logicify/healthcheckbot:$TRAVIS_TAG --build-arg="VERSION=$TRAVIS_TAG" .
- ./build.sh docker-push